% clear all; 
close all;
fprintf('Prepare for the original image : I binary image : bI\n');
clear opts; 
opts.useabsolute = 0; 
opts.responsetype = 3; 
opts.normalizationtype = 1;
load('zebraI.mat');
radius = 1 : 3; 
hessian_out = oof3response(double(I), radius, opts);
thresholdoof = 0.1;
B = hessian_out > thresholdoof; 
[x y z] = ind2sub(size(B), find(B));
plot3(y, x, z, '.', 'Color', [0.7 0.7 1]);  view(3); axis equal;
clear opts;
clear radius;
clear x;
clear y;
clear z;
clear thresholdoof;
I = B;
clear B;
clear hessian_out;